---
- hosts: ansible_ubuntu
  gather_facts: false
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Update packages using apt
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 86400 #One day